### ISSUE TITLE
Resize image?

### ISSUE THREAD

**Issue by iffy** [jangko/nimPNG#29]
Would a PR to resize images be accepted here?  Or is that beyond the scope of this module?

Edit: I should add that I have no idea how to do it.  But I may be motivated enough to figure it out. :)

**Comment by jangko** [comment]
I'm glad you have such motivation, but image scaling/resizing is not something easy, there are many filter/algorithm. And I'm afraid all of them fall into the realm of image processing/rendering.

one of the main purpose of PNG is to preserve pixel data intact because PNG use lossless compression,
scaling/resizing will make the pixel data altered.

But I don't want to kill your motivation either, perhaps you can working with APNG offset and alpha rendering(please read the readme.md and APNG spec). They are fairly easy and can be implemented on top of existing API without knowing to much about the underlying details.

If you already mastered this technique, then you'll have very good foundation to understand resizing/scaling problem.

in the tests folder there is minibmp.nim, you can use that to produce the result of the rendering. your work will become additional tools for nimPNG that is still inside the scope of this library.

**Comment by bung87** [comment]
https://github.com/SolitudeSF/imageman/blob/master/src/imageman/resize.nim I think this file can be ported to nimPNG

**Comment by jangko** [comment]
no need to port them, you can use `nimPNG` and `imageman` together. You only need to convert `PNGResult` to imageman `Image` with `RGBAU` colorspace. And with some pointer tricks, you actually can have almost free conversion.

example:
```Nim
type
   MyImage = ref Image[ColorRGBAU]

let png = loadPNG32("pngfile.png")
let img = cast[MyImage](png)

let res = resizeBilinear(img[], target_w, target_h)
```

**Comment by bung87** [comment]
that's cool , there's problem `imageman` relys on `libpng` which is not pure, would it acceptable to make a PR port of resize.nim?

**Comment by jangko** [comment]
you can safely import imageman's `images` and `colors` module and use it with `nimPNG`, if LTO(link time optimization) works properly. no need to worry libpng will be included in your final binary.

no need to port it.

**Comment by bung87** [comment]
Thanks! helpfull , that type casting is magic. solve my problem.

**Comment by bung87** [comment]
I have another problem , how to construct PNG(or encode png bytes) from `MyImage` I need pass it to my `optimizePNG` proc or save it somewhere directly, if I use `imageman` when writePng it will need libpng.

**Comment by jangko** [comment]
I assume you get the image after resizing then it would be something like this:

```Nim
type
   MyImage = ref Image[ColorRGBAU]
   TImage = ptr object
      width: int
      height: int
      pixels: seq[uint8]

let png = loadPNG32("pngfile.png")
let img = cast[MyImage](png)

var res = resizeBilinear(img[], target_w, target_h)
let timg = cast[TImage](unsafeAddr(res))
var r = savePNG32("filename.png", timg.pixels, timg.width, timg.height)
if r.isOK:
   # do something
else:
  # do something
```

tips: as long as the target object have similar structure/size, you can cast it using pointer(no copies), or using object if you can afford copies. you can read more about this trick from C programming language manual.

**Comment by bung87** [comment]
I got `unhandled exception: not enough input to encode [PNGError]` whether `encodePNG`  or `savePNG32`, I suppose to store it in memory and pass to next proc, 
yeah, that tips helpful, `seq[ColorRGBAU]` cast to `string` surprised me , since ColorRGBAU is 4 components, I check the source it's array so it's just bytes

**Comment by jangko** [comment]
the pixels element length should be w x h x 4 for RGBAU and w x h x 3 for RGBU.

**Comment by bung87** [comment]
yeah, casting can't adjust that seq size , that cause this , I'll retry later . use copymem or something else.
